// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: send_to_push_message.proto

package person.rulo.flink.learning.dstreamapi.proto;

public final class PushMessageProto {
  private PushMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PushMessageMqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PushMessageMq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>required string messageId = 1;</code>
     */
    boolean hasMessageId();
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>required string messageId = 1;</code>
     */
    String getMessageId();
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>required string messageId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>required string taskId = 2;</code>
     */
    boolean hasTaskId();
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>required string taskId = 2;</code>
     */
    String getTaskId();
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>required string taskId = 2;</code>
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <pre>
     * 推送目标类型， IMEI:-1, REGISTRATION_ID:2, DUID:-9, OUID:-11
     * </pre>
     *
     * <code>required int32 targetType = 3;</code>
     */
    boolean hasTargetType();
    /**
     * <pre>
     * 推送目标类型， IMEI:-1, REGISTRATION_ID:2, DUID:-9, OUID:-11
     * </pre>
     *
     * <code>required int32 targetType = 3;</code>
     */
    int getTargetType();

    /**
     * <pre>
     * 1000条IMEI或REGID, 用逗号分隔
     * </pre>
     *
     * <code>required string targetValue = 4;</code>
     */
    boolean hasTargetValue();
    /**
     * <pre>
     * 1000条IMEI或REGID, 用逗号分隔
     * </pre>
     *
     * <code>required string targetValue = 4;</code>
     */
    String getTargetValue();
    /**
     * <pre>
     * 1000条IMEI或REGID, 用逗号分隔
     * </pre>
     *
     * <code>required string targetValue = 4;</code>
     */
    com.google.protobuf.ByteString
        getTargetValueBytes();

    /**
     * <pre>
     * 推送类型， 标签推送：1, 个性化推送：2
     * </pre>
     *
     * <code>required int32 pushType = 5;</code>
     */
    boolean hasPushType();
    /**
     * <pre>
     * 推送类型， 标签推送：1, 个性化推送：2
     * </pre>
     *
     * <code>required int32 pushType = 5;</code>
     */
    int getPushType();

    /**
     * <pre>
     * 推送目标总数， 每个消息包都需要传
     * </pre>
     *
     * <code>required int32 targetCount = 6;</code>
     */
    boolean hasTargetCount();
    /**
     * <pre>
     * 推送目标总数， 每个消息包都需要传
     * </pre>
     *
     * <code>required int32 targetCount = 6;</code>
     */
    int getTargetCount();
  }
  /**
   * Protobuf type {@code PushMessageMq}
   */
  public  static final class PushMessageMq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PushMessageMq)
      PushMessageMqOrBuilder {
    // Use PushMessageMq.newBuilder() to construct.
    private PushMessageMq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PushMessageMq() {
      messageId_ = "";
      taskId_ = "";
      targetType_ = 0;
      targetValue_ = "";
      pushType_ = 0;
      targetCount_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PushMessageMq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              messageId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              taskId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              targetType_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              targetValue_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              pushType_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              targetCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PushMessageProto.internal_static_PushMessageMq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PushMessageProto.internal_static_PushMessageMq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PushMessageMq.class, Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private volatile Object messageId_;
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>required string messageId = 1;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>required string messageId = 1;</code>
     */
    public String getMessageId() {
      Object ref = messageId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>required string messageId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKID_FIELD_NUMBER = 2;
    private volatile Object taskId_;
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>required string taskId = 2;</code>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>required string taskId = 2;</code>
     */
    public String getTaskId() {
      Object ref = taskId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>required string taskId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGETTYPE_FIELD_NUMBER = 3;
    private int targetType_;
    /**
     * <pre>
     * 推送目标类型， IMEI:-1, REGISTRATION_ID:2, DUID:-9, OUID:-11
     * </pre>
     *
     * <code>required int32 targetType = 3;</code>
     */
    public boolean hasTargetType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 推送目标类型， IMEI:-1, REGISTRATION_ID:2, DUID:-9, OUID:-11
     * </pre>
     *
     * <code>required int32 targetType = 3;</code>
     */
    public int getTargetType() {
      return targetType_;
    }

    public static final int TARGETVALUE_FIELD_NUMBER = 4;
    private volatile Object targetValue_;
    /**
     * <pre>
     * 1000条IMEI或REGID, 用逗号分隔
     * </pre>
     *
     * <code>required string targetValue = 4;</code>
     */
    public boolean hasTargetValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 1000条IMEI或REGID, 用逗号分隔
     * </pre>
     *
     * <code>required string targetValue = 4;</code>
     */
    public String getTargetValue() {
      Object ref = targetValue_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetValue_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 1000条IMEI或REGID, 用逗号分隔
     * </pre>
     *
     * <code>required string targetValue = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTargetValueBytes() {
      Object ref = targetValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        targetValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUSHTYPE_FIELD_NUMBER = 5;
    private int pushType_;
    /**
     * <pre>
     * 推送类型， 标签推送：1, 个性化推送：2
     * </pre>
     *
     * <code>required int32 pushType = 5;</code>
     */
    public boolean hasPushType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * 推送类型， 标签推送：1, 个性化推送：2
     * </pre>
     *
     * <code>required int32 pushType = 5;</code>
     */
    public int getPushType() {
      return pushType_;
    }

    public static final int TARGETCOUNT_FIELD_NUMBER = 6;
    private int targetCount_;
    /**
     * <pre>
     * 推送目标总数， 每个消息包都需要传
     * </pre>
     *
     * <code>required int32 targetCount = 6;</code>
     */
    public boolean hasTargetCount() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * 推送目标总数， 每个消息包都需要传
     * </pre>
     *
     * <code>required int32 targetCount = 6;</code>
     */
    public int getTargetCount() {
      return targetCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTaskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTargetType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTargetValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPushType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTargetCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, targetType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, targetValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, pushType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, targetCount_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, targetType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, targetValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, pushType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, targetCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PushMessageMq)) {
        return super.equals(obj);
      }
      PushMessageMq other = (PushMessageMq) obj;

      boolean result = true;
      result = result && (hasMessageId() == other.hasMessageId());
      if (hasMessageId()) {
        result = result && getMessageId()
            .equals(other.getMessageId());
      }
      result = result && (hasTaskId() == other.hasTaskId());
      if (hasTaskId()) {
        result = result && getTaskId()
            .equals(other.getTaskId());
      }
      result = result && (hasTargetType() == other.hasTargetType());
      if (hasTargetType()) {
        result = result && (getTargetType()
            == other.getTargetType());
      }
      result = result && (hasTargetValue() == other.hasTargetValue());
      if (hasTargetValue()) {
        result = result && getTargetValue()
            .equals(other.getTargetValue());
      }
      result = result && (hasPushType() == other.hasPushType());
      if (hasPushType()) {
        result = result && (getPushType()
            == other.getPushType());
      }
      result = result && (hasTargetCount() == other.hasTargetCount());
      if (hasTargetCount()) {
        result = result && (getTargetCount()
            == other.getTargetCount());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessageId()) {
        hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
        hash = (53 * hash) + getMessageId().hashCode();
      }
      if (hasTaskId()) {
        hash = (37 * hash) + TASKID_FIELD_NUMBER;
        hash = (53 * hash) + getTaskId().hashCode();
      }
      if (hasTargetType()) {
        hash = (37 * hash) + TARGETTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getTargetType();
      }
      if (hasTargetValue()) {
        hash = (37 * hash) + TARGETVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getTargetValue().hashCode();
      }
      if (hasPushType()) {
        hash = (37 * hash) + PUSHTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getPushType();
      }
      if (hasTargetCount()) {
        hash = (37 * hash) + TARGETCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getTargetCount();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PushMessageMq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PushMessageMq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PushMessageMq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PushMessageMq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PushMessageMq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PushMessageMq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PushMessageMq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PushMessageMq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PushMessageMq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PushMessageMq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PushMessageMq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PushMessageMq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PushMessageMq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PushMessageMq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PushMessageMq)
        PushMessageMqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PushMessageProto.internal_static_PushMessageMq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PushMessageProto.internal_static_PushMessageMq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PushMessageMq.class, Builder.class);
      }

      // Construct using person.rulo.flink.learning.dstreamapi.proto.PushMessageProto.PushMessageMq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        taskId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        targetType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        targetValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        pushType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        targetCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PushMessageProto.internal_static_PushMessageMq_descriptor;
      }

      public PushMessageMq getDefaultInstanceForType() {
        return PushMessageMq.getDefaultInstance();
      }

      public PushMessageMq build() {
        PushMessageMq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PushMessageMq buildPartial() {
        PushMessageMq result = new PushMessageMq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.taskId_ = taskId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.targetType_ = targetType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.targetValue_ = targetValue_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.pushType_ = pushType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.targetCount_ = targetCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PushMessageMq) {
          return mergeFrom((PushMessageMq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PushMessageMq other) {
        if (other == PushMessageMq.getDefaultInstance()) return this;
        if (other.hasMessageId()) {
          bitField0_ |= 0x00000001;
          messageId_ = other.messageId_;
          onChanged();
        }
        if (other.hasTaskId()) {
          bitField0_ |= 0x00000002;
          taskId_ = other.taskId_;
          onChanged();
        }
        if (other.hasTargetType()) {
          setTargetType(other.getTargetType());
        }
        if (other.hasTargetValue()) {
          bitField0_ |= 0x00000008;
          targetValue_ = other.targetValue_;
          onChanged();
        }
        if (other.hasPushType()) {
          setPushType(other.getPushType());
        }
        if (other.hasTargetCount()) {
          setTargetCount(other.getTargetCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageId()) {
          return false;
        }
        if (!hasTaskId()) {
          return false;
        }
        if (!hasTargetType()) {
          return false;
        }
        if (!hasTargetValue()) {
          return false;
        }
        if (!hasPushType()) {
          return false;
        }
        if (!hasTargetCount()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PushMessageMq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PushMessageMq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object messageId_ = "";
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>required string messageId = 1;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>required string messageId = 1;</code>
       */
      public String getMessageId() {
        Object ref = messageId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>required string messageId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>required string messageId = 1;</code>
       */
      public Builder setMessageId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>required string messageId = 1;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>required string messageId = 1;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }

      private Object taskId_ = "";
      /**
       * <pre>
       *任务ID
       * </pre>
       *
       * <code>required string taskId = 2;</code>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *任务ID
       * </pre>
       *
       * <code>required string taskId = 2;</code>
       */
      public String getTaskId() {
        Object ref = taskId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *任务ID
       * </pre>
       *
       * <code>required string taskId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *任务ID
       * </pre>
       *
       * <code>required string taskId = 2;</code>
       */
      public Builder setTaskId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *任务ID
       * </pre>
       *
       * <code>required string taskId = 2;</code>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *任务ID
       * </pre>
       *
       * <code>required string taskId = 2;</code>
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        taskId_ = value;
        onChanged();
        return this;
      }

      private int targetType_ ;
      /**
       * <pre>
       * 推送目标类型， IMEI:-1, REGISTRATION_ID:2, DUID:-9, OUID:-11
       * </pre>
       *
       * <code>required int32 targetType = 3;</code>
       */
      public boolean hasTargetType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 推送目标类型， IMEI:-1, REGISTRATION_ID:2, DUID:-9, OUID:-11
       * </pre>
       *
       * <code>required int32 targetType = 3;</code>
       */
      public int getTargetType() {
        return targetType_;
      }
      /**
       * <pre>
       * 推送目标类型， IMEI:-1, REGISTRATION_ID:2, DUID:-9, OUID:-11
       * </pre>
       *
       * <code>required int32 targetType = 3;</code>
       */
      public Builder setTargetType(int value) {
        bitField0_ |= 0x00000004;
        targetType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 推送目标类型， IMEI:-1, REGISTRATION_ID:2, DUID:-9, OUID:-11
       * </pre>
       *
       * <code>required int32 targetType = 3;</code>
       */
      public Builder clearTargetType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        targetType_ = 0;
        onChanged();
        return this;
      }

      private Object targetValue_ = "";
      /**
       * <pre>
       * 1000条IMEI或REGID, 用逗号分隔
       * </pre>
       *
       * <code>required string targetValue = 4;</code>
       */
      public boolean hasTargetValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 1000条IMEI或REGID, 用逗号分隔
       * </pre>
       *
       * <code>required string targetValue = 4;</code>
       */
      public String getTargetValue() {
        Object ref = targetValue_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            targetValue_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 1000条IMEI或REGID, 用逗号分隔
       * </pre>
       *
       * <code>required string targetValue = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTargetValueBytes() {
        Object ref = targetValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          targetValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 1000条IMEI或REGID, 用逗号分隔
       * </pre>
       *
       * <code>required string targetValue = 4;</code>
       */
      public Builder setTargetValue(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        targetValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1000条IMEI或REGID, 用逗号分隔
       * </pre>
       *
       * <code>required string targetValue = 4;</code>
       */
      public Builder clearTargetValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        targetValue_ = getDefaultInstance().getTargetValue();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1000条IMEI或REGID, 用逗号分隔
       * </pre>
       *
       * <code>required string targetValue = 4;</code>
       */
      public Builder setTargetValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        targetValue_ = value;
        onChanged();
        return this;
      }

      private int pushType_ ;
      /**
       * <pre>
       * 推送类型， 标签推送：1, 个性化推送：2
       * </pre>
       *
       * <code>required int32 pushType = 5;</code>
       */
      public boolean hasPushType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * 推送类型， 标签推送：1, 个性化推送：2
       * </pre>
       *
       * <code>required int32 pushType = 5;</code>
       */
      public int getPushType() {
        return pushType_;
      }
      /**
       * <pre>
       * 推送类型， 标签推送：1, 个性化推送：2
       * </pre>
       *
       * <code>required int32 pushType = 5;</code>
       */
      public Builder setPushType(int value) {
        bitField0_ |= 0x00000010;
        pushType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 推送类型， 标签推送：1, 个性化推送：2
       * </pre>
       *
       * <code>required int32 pushType = 5;</code>
       */
      public Builder clearPushType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pushType_ = 0;
        onChanged();
        return this;
      }

      private int targetCount_ ;
      /**
       * <pre>
       * 推送目标总数， 每个消息包都需要传
       * </pre>
       *
       * <code>required int32 targetCount = 6;</code>
       */
      public boolean hasTargetCount() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       * 推送目标总数， 每个消息包都需要传
       * </pre>
       *
       * <code>required int32 targetCount = 6;</code>
       */
      public int getTargetCount() {
        return targetCount_;
      }
      /**
       * <pre>
       * 推送目标总数， 每个消息包都需要传
       * </pre>
       *
       * <code>required int32 targetCount = 6;</code>
       */
      public Builder setTargetCount(int value) {
        bitField0_ |= 0x00000020;
        targetCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 推送目标总数， 每个消息包都需要传
       * </pre>
       *
       * <code>required int32 targetCount = 6;</code>
       */
      public Builder clearTargetCount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        targetCount_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PushMessageMq)
    }

    // @@protoc_insertion_point(class_scope:PushMessageMq)
    private static final PushMessageMq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PushMessageMq();
    }

    public static PushMessageMq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<PushMessageMq>
        PARSER = new com.google.protobuf.AbstractParser<PushMessageMq>() {
      public PushMessageMq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PushMessageMq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PushMessageMq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PushMessageMq> getParserForType() {
      return PARSER;
    }

    public PushMessageMq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushMessageMq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PushMessageMq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032send_to_push_message.proto\"\202\001\n\rPushMes" +
      "sageMq\022\021\n\tmessageId\030\001 \002(\t\022\016\n\006taskId\030\002 \002(" +
      "\t\022\022\n\ntargetType\030\003 \002(\005\022\023\n\013targetValue\030\004 \002" +
      "(\t\022\020\n\010pushType\030\005 \002(\005\022\023\n\013targetCount\030\006 \002(" +
      "\005B?\n+person.rulo.flink.learning.dstreama" +
      "pi.protoB\020PushMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PushMessageMq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PushMessageMq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PushMessageMq_descriptor,
        new String[] { "MessageId", "TaskId", "TargetType", "TargetValue", "PushType", "TargetCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
